name: Build and push Docker image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the release version and date
        id: vars
        run: |
          echo "::set-output name=version::${{ github.event.release.tag_name }}"
          echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/sonosantiabuse:latest
            ghcr.io/${{ github.repository }}/sonosantiabuse:${{ github.event.release.tag_name }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            DATE=${{ steps.vars.outputs.date }}
